language: emacs-lisp

os:
  - osx

matrix:
  include:
    # Emacs 26.x on Mojave (10.14)
    - env:
        - BUILD_OPTIONS=""
        - TEST_OPTIONS=""
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - gnupg
          update: true

    # Emacs 27.x on Mojave (10.14)
    - env:
        - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson"
        - TEST_OPTIONS="--HEAD"
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - gnupg
          update: true

  fast_finish: true

before_script:
  - mv ../emacs-config ~/.emacs.d
  - mv ~/.emacs.d/personal.el.example ~/.emacs.d/personal.el
  - brew tap daviderestivo/emacs-head
  - travis_wait 60 brew install emacs-head $BUILD_OPTIONS

script:
  - echo "Attempting startup..."
  - emacs -nw --batch --eval='(let ((debug-on-error (>=  emacs-major-version 26))
                                    (url-show-status nil)
                                    (initial-buffer-choice "*scratch*")
                                    (user-emacs-directory default-directory)
                                    (user-init-file (expand-file-name "init.el")))
                                (package-initialize)
                                (load-file "~/.emacs.d/init.el")
                                (message "... startup successful!"))'
