language: generic

os:
  - osx

# Handle git submodules yourself
git:
    submodules: false

jobs:
  include:
    # Emacs 26.x on Catalina (10.15)
    - env:
        - BUILD_OPTIONS="emacs-head"
      osx_image: xcode11.5
      addons:
        homebrew:
          packages:
            - gnupg
          update: true

    # Emacs 27.x on Catalina (10.15)
    - env:
        - BUILD_OPTIONS="emacs-head@27"
      osx_image: xcode11.5
      addons:
        homebrew:
          packages:
            - gnupg
          update: true

    # Emacs 28.x on Catalina (10.15)
    - env:
        - BUILD_OPTIONS="emacs-head@28 --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-pdumper --with-xwidgets"
      osx_image: xcode11.5
      addons:
        homebrew:
          packages:
            - gnupg
          update: true

  fast_finish: true

before_script:
  - echo "Current working directory..."
  - echo $PWD
  - mv ../galactic-emacs ~/.emacs.d
  - mv ~/.emacs.d/personal.el.example ~/.emacs.d/personal.el
  - brew tap daviderestivo/emacs-head
  - travis_wait 60 brew install $BUILD_OPTIONS

script:
  - echo "Attempting startup..."
  - echo "Changing working directory to \"~/.emacs.d\"..."
  - cd ~/.emacs.d
  - echo $PWD
  - git submodule init && git submodule update && git submodule foreach --recursive git checkout master
  - emacs -nw --batch --eval='(let ((debug-on-error (>=  emacs-major-version 26))
                                    (url-show-status nil)
                                    (initial-buffer-choice "*scratch*")
                                    (user-emacs-directory default-directory)
                                    (user-init-file (expand-file-name "init.el")))
                                (package-initialize)
                                (load-file "~/.emacs.d/init.el")
                                (message "... startup successful!"))'
