language: emacs-lisp

os:
  - osx

# Handle git submodules yourself
git:
    submodules: false

matrix:
  include:
    # Emacs 26.x on Mojave (10.14)
    - env:
        - BUILD_OPTIONS=""
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
            - gnupg
          update: true

    # Emacs 27.x on Mojave (10.14)
    - env:
        - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson"
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
            - gnupg
          update: true

  fast_finish: true

before_script:
  - echo "Current working directory..."
  - echo $PWD
  - mv ../galactic-emacs ~/.emacs.d
  - mv ~/.emacs.d/personal.el.example ~/.emacs.d/personal.el
  - brew unlink python@2
  - brew tap daviderestivo/emacs-head
  - travis_wait 60 brew install emacs-head $BUILD_OPTIONS

script:
  - echo "Attempting startup..."
  - echo "Changing working directory to \"~/.emacs.d\"..."
  - cd ~/.emacs.d
  - echo $PWD
  - git submodule init && git submodule update && git submodule foreach --recursive git checkout master
  - emacs -nw --batch --eval='(let ((debug-on-error (>=  emacs-major-version 26))
                                    (url-show-status nil)
                                    (initial-buffer-choice "*scratch*")
                                    (user-emacs-directory default-directory)
                                    (user-init-file (expand-file-name "init.el")))
                                (package-initialize)
                                (load-file "~/.emacs.d/init.el")
                                (message "... startup successful!"))'
